[package]
name = "flower_examples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flower = { version = "0.1.0-alpha.1", path = "../flower" }