[package]
name = "flower"
version = "0.1.0-alpha.1"
edition = "2021"
authors = ["Misaka 15535"]
license = "GLWTPL"
description = """
Try making a cross-platform GUI library.
"""
readme = "README.md"
keywords = ["opengl", "gui"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.9.0"
# 少量数据时查询速度更快的map
rustc-hash = { version = "1.0" }
log = "0.4"
glutin = "0.28.0"

#[target.'cfg(windows)'.dependencies]
#windows = { path = "../native/windows", version = "=0.1.0" }
takeable-option = "0.4"
gleam = "0.14.0"
[build-dependencies]
gl_generator = "0.14"

[[example]]
name = "test"