[package]
name = "flower"
version = "0.1.0-alpha.1"
edition = "2021"
authors = ["Misaka 15535"]
license = "GLWTPL"
description = """
Try making a cross-platform GUI library.
"""
readme = "README.md"
keywords = ["opengl", "gui"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#miniquad = "0.3.0-alpha.43"
once_cell = "1.9.0"
# 少量数据时查询速度更快的map
rustc-hash = { version = "1.0" }

[target.'cfg(windows)'.dependencies]
windows = { path = "../native/windows", version = "=0.1.0" }

[[example]]
name = "test"